services:
  db:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      RAILS_ENV: production
    volumes:
      - ./backend:/app
      - uploads_data:/app/public/uploads
      - tmp_data:/app/tmp
    expose:
      - "3000"
    depends_on:
      - db
    stdin_open: true
    tty: true

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mysql_data:
  uploads_data:
  tmp_data:
